### ISSUE TITLE
OperationalError

### ISSUE THREAD

**Issue by saksham2410** [makai554892700/TelegramPython#2]
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'telegram'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)

When I try to do python3 manage.py db migrate

**Comment by makai554892700** [comment]
I think your mysql`s pass is not right.And you need to create telegram user and telegram database.
Thanks.
